### ISSUE TITLE
Chomukij

### ISSUE THREAD

**Issue by JesusTiag0** [Leinad4Mind/leinad4mind-addons#10]
Bom dia,

Sempre usei o add on da chomiteca para aceder a minhateca, desde que saiu do ar uso para aceder ao chomikuj, mas agora não dá para aceder, diz-me não disponivel, nem para aceder aos meus ficheiros, nem de outros utilizadores.

Será erro do site ?

Obrigado

**Comment by JesusTiag0** [comment]
Boa tarde,

Seria possivel obter alguma resposta sobre este assunto ?

Se não houver solução deixo de fazer upload dos filmes para o alojamento, visto que não os posso ver em streaming.

**Comment by Leinad4Mind** [comment]
Em breve sairá nova versão. Talvez Domingo, sem promessas.

**Comment by JesusTiag0** [comment]
Obrigado pela resposta, assim já posso continuar a fazer Upload de filmes. obrigado pelo bom trabalho feito. 👍

**Comment by Leinad4Mind** [comment]
@JesusTiag0 ainda tens o mesmo problema? Estive a analisar e não encontrei problemas.
De qualquer forma tive a remover o Minhateca e em breve haverá nova versão, no entanto se tiveres algum problema actualmente, diz.

**Comment by Leinad4Mind** [comment]
Nova versão lançada vou assumir que este erro aqui esteja resolvido.
