### ISSUE TITLE
Error chomiteca

### ISSUE THREAD

**Issue by eraser-head** [Leinad4Mind/leinad4mind-addons#11]
Hi. New releases show me always the same error, I can't access to the files if they aren't in root folder, if they are in any sub folders, I can't access to him, I attach kodi log. Thanks in advance.

PD, with older version 1.5.0 works fine, but I can't see the names of the files, only show "oce plik" names in all files. I try clean install, same result.

[kodi.log](https://github.com/Leinad4Mind/leinad4mind-addons/files/3969585/kodi.log)

**Comment by eraser-head** [comment]
by the way, the addon looks like block a some combination key on my remote keypad, if I start kodi, some Function key doesn't works, in kodi and windows, doesn't matter if I use the addon or not.

**Comment by Leinad4Mind** [comment]
I'll take a look this weekend.

Thanks for using and reporting.

**Comment by eraser-head** [comment]
> 
> 
> I'll take a look this weekend.
> 
> Thanks for using and reporting.

thanks, forguet the last repost, it's my pc working not fine, the remote pad works ok in other pc with chomiteca installed, but the first issue with your addon happens in both pc.

Cheers

**Comment by eraser-head** [comment]
any news?

**Comment by Leinad4Mind** [comment]
I've added a new folder named "El padrino de Harlem (2019)" inside a new folder called "Season 1" to be as your error. But I am able to enter and to play the video I uploaded. I can't reproduce the error.

Could you change the login and share the account with me?

Orelse take a printscreen to your folder and filenames so I can see the structure and try to replicate here.

Send me the data through this form: https://leinad4mind.top/forum/contact.html

**Comment by Leinad4Mind** [comment]
Btw I saw now that you've 1.5.0, last version is 1.6.1
