### ISSUE TITLE
Chomiteca Italian Language Done!

### ISSUE THREAD

**Issue by mestesso93** [Leinad4Mind/leinad4mind-addons#12]
I've made Italian Translate for chomiteca! Thank you for this awesome addon!

https://pastebin.com/CbCR0Vvp

obviously "en" in "Language" must be changed in "it".

Bye!

**Comment by woully** [comment]
I made the Spanish translation too.

https://pastebin.com/TihtqdSB

Regards

**Comment by Leinad4Mind** [comment]
Both languages added thank you for the contribution
