### ISSUE TITLE
Chomiteca in Kodi Matrix and Nexus?

### ISSUE THREAD

**Issue by woully** [Leinad4Mind/leinad4mind-addons#14]
Since version19 Matrix, Kodi only support python 3 instead python 2. So many addons, like chomiteca, dont work in the newest versions of Kodi.

Im not a code expert but i see that python 3 introduced some diferences with v2 and i could give a hand to make an update for chomiteca to v3

Best regards

**Comment by Leinad4Mind** [comment]
I already converted all my addons to python 3 I should make them available soon.
I stopped the development since I didnt receibv any kind of appreciation about them in 10 years so I assumed no one wanted the addons...

**Comment by Deci8BelioS** [comment]
> I already converted all my addons to python 3 I should make them available soon. I stopped the development since I didnt receibv any kind of appreciation about them in 10 years so I assumed no one wanted the addons...

This is really good news, I've been using chomiteca for years, recently I made a javascript script with an AI to scrape urls and save them in .strm files as chomiteca does, but this automatically changes pages and subfolders of series I can give you as thanks for the addon chomiteca that despite being since 2020 without updating (kodi version 18.9) still works.

**Comment by Deci8BelioS** [comment]
> I already converted all my addons to python 3 I should make them available soon. I stopped the development since I didnt receibv any kind of appreciation about them in 10 years so I assumed no one wanted the addons...

Great news, I'll keep an eye out for the chomiteca addon, I can't wait to use it on kodi 20!

**Comment by Leinad4Mind** [comment]
I decided to make them all available through my website here: https://leinad4mind.top/forum/

Hope it helps

**Comment by Deci8BelioS** [comment]
> I decided to make them all available through my website here: https://leinad4mind.top/forum/
> 
> Hope it helps

I registered in the forum but it tells me that the account is not active.

**Comment by Leinad4Mind** [comment]
You'll eventually receive an email to confirm the registration

**Comment by Deci8BelioS** [comment]
> You'll eventually receive an email to confirm the registration

The email I received says: Your account is currently inactive and will need to be approved by an administrator before you can log in.
administrator before you can log in. Another email will be sent when this
this has occurred.
