### ISSUE TITLE
Scraping with errors CHOMITECA [SOLVED]

### ISSUE THREAD

**Issue by Deci8BelioS** [Leinad4Mind/leinad4mind-addons#16]
Hello again, in the latest premium version of chomiteca, when exporting the .strm files they appear with titles like this:

_Alicia+en+el+PaÃ+s+de+las+Maravillas+(2010).strm_

Agente+007+contra+el+Dr.+No+(1962).strm_

In the addon's file explorer the titles appear like this:

Alicia en el Pa&#237 ;s de las Maravillas (2010).mkv

(the number and ;s go together, which appears here as well as I left it together)

this is the original title

_Alicia en el País de las Maravillas (2010).mkv_

For series with accents or special characters, the title is also displayed like this, for example:

_Bastard Heavy Metal, FantasÃa Oscura_

The original title is:

_Bastard -Heavy Metal, Fantasía Oscura_

**Comment by Leinad4Mind** [comment]
Can you let me know the steps that I need to do? Already forgot how to work with strm files :'(

**Comment by Deci8BelioS** [comment]
You browse your account directory, go to a folder where the mkv files are for example, open the context menu and Add to library - Batch and it will generate the .strm files in the chomiteca profile data folder.

**Comment by Leinad4Mind** [comment]
New release available
- Fix images options
- Fix accents bug
- Added new option to disable globally images for better performance
- Improve logs
- Improve seasons detections

**Comment by Leinad4Mind** [comment]
So about strm, now I guess I got it. You create them inside more then one plugin if needed and then you create a video source and point to the folder with strm, so you can have a library from multiple sources.

**Comment by Deci8BelioS** [comment]
Yes, it is to use the kodi interface to have the movies and series with their covers.

![image](https://user-images.githubusercontent.com/96150975/234478654-41619336-1038-4a11-908a-bf773febe397.png)
 
and the .strm files contain the link to the file in chomikuj

**Comment by Deci8BelioS** [comment]
I have been modifying the "def add_to_library" the final part which would be 

"if type == 'movie': save_file(clean_url(clean_title(title))+'.strm',strm_contents,file_folder)
 if type == 'tvshow': save_file((urllib.parse.unquote_plus(title))+'.strm',strm_contents,file_folder)"

and also
 "def clean_title(title):
    decoded_title = urllib.parse.unquote(title)
    cleaned_title = replace_special_char_extra(decoded_title)
    return cleaned_title"

the movies screapea them well with the name well without the "+" as spaces but in the series screapea a single episode (a single file .strm) and I do not know why it is (besides it sneaks a %2C in the url that is inside the .strm, although the script to open the url cleans it and loads the episode), if I activate in the addon settings to keep the name of the episodes screapea all episodes without problems

I have 0 programming knowledge, I have used the AI without much success xd

"Screapea = Scraping" more or less.

**Comment by Deci8BelioS** [comment]
I have managed to solve the issue of scraping movies and series with the AI, I'll send you a PM from his website if you want to take a look and add it to the script.

**Comment by Deci8BelioS** [comment]
Can you confirm that you got the PM? I noticed that you didn't get the Spanish translation xddd

**Comment by Leinad4Mind** [comment]
Yes I confirm. Didnt had free time lately.

**Comment by Deci8BelioS** [comment]
> Yes I confirm. Didnt had free time lately.

No problem don't worry. 

You should have received a PM by now with "big" changes to the addon.

**Comment by Deci8BelioS** [comment]
This issues can be closed since the scraping is solved xd

If you replied to my PM on the web I have not received it (I'll let you know just in case).
