### ISSUE TITLE
Apresentar Capas

### ISSUE THREAD

**Issue by JesusTiag0** [Leinad4Mind/leinad4mind-addons#3]
Bom dia, antes de mais muitos parabens pelo Addon, mas gostaria de saber se seria possivel o addon começar a apresentar as capas dos filmes. Por exemplo, na nossa conta junto com o ficheiro do filme com o mesmo nome um ficheiro .JPG e assim ficavamos com a capa do filme igual ao addon Genesis.
É apenas um pedido não sei se sera possivel se nao.

**Comment by Leinad4Mind** [comment]
Sim, é possível. Também já tinha pensado fazer isso mesmo. Obrigado pela sugestão de qualquer forma.

**Comment by Leinad4Mind** [comment]
A única forma simples de se conseguir isso seria tendo as imagens num servidor próprio,
onde as imagens teriam o mesmo nome que o ficheiro de vídeo.

Pois não vejo forma de capturar todos os títulos dos ficheiros e compará-los. Pois isto está feito para comparar página a página. E no máximo iria conseguir-se comparar o titulo do ficheiro com o seguinte da lista. Mas ainda assim seria uma mudança grande de código... 

Ao ter servidor próprio seria possível ter os vídeos a ir buscar ao servidor essas imagens e no caso da imagem não existir no servidor apareceria a imagem padrão.

É que eu consigo no máximo adicionar a imagem do ficheiro em questão de momento: http://i.imgur.com/2QXYKLX.png

As imagens iriam aparecer bem. Os vídeos mp4 têm uma espécie de screenshots. E se for mkv o minhateca nem sempre consegue ir buscar imagem... e ficaria como a do canto superior direito.

Daí que pessoalmente prefiro não ter nenhuma imagem do que este resultado sem padronização nenhuma... daí ter optado pela padronização sem aparecer estas imagens.

Poderia sim era adicionar uma opção para cada um poder adicionar um servidor de imagens.
Dessa forma já seria possível as imagens aparecerem bem, para essas pessoas que o configurassem.

**Comment by JesusTiag0** [comment]
Boa noite, peço desculpa mas não percebi qual a alternativa de meter um servidor de imagens, no meu caso uso o kodi com o tema aeon fica assim http://i.imgur.com/7sWE21N.png e o que eu sugeria é que ficasse algo deste genero http://i.imgur.com/mW7WzC7.png como nao percebo grande coisa de programação não sei qual será o custo de fazer esta alteração ao add on, que por sua vez esta muito bom mesmo.

Outra duvida é que na minha conta tenho todos os filmes em pastas, ou seja, tenho uma pasta principal e dentro dela as pastas cada uma com o seu filme lá dentro, seria possivel adicionar fotografias referentes a uma pasta ou teria mesmo que ser apenas referente ao ficheiro ? Não sei se me estou a fazer entender bem.

Mas penso que era uma mais valia, se a opção que propôs fosse fácil de se fazer, e se pudéssemos adicionar manualmente as capas aos filmes da nossa própria conta seria muito bom mesmo.

Desde já agradeço pela resposta a minha duvida e aguardo algum feedback. 

Obrigado

**Comment by Leinad4Mind** [comment]
Boa noite, a última versão já permite adicionar manualmente as capas. Agora em vez de colocar a capa no minhateca/chomikuj, terá de adicionar ou num servidor próprio. Iria custar lhe 30 euros ao ano oara ter um.

Ou poderá colocar no seu Kodi.
Eu adicionei as 2 opções. Servidor ou caminho local. Como não deve ter servidor e caso não deseje ter gastos. Então basta usar o caminho local. Leia o changelog tem lá a indicar o caminho da pasta onde se deve colocar as imagens. E se a imagem tiver o mesmo nome que o vídeo ela irá surgir tal como deseja.

Se por ventura arranjar forma de ir buscar automaticamente a imagem a pasta já que no seu caso só tem 1 img por pasta eu lançarei nova versão com essa possibilidade.

Mas com algum trabalho extra tb ja poderá ter as imagens :p

Cumprimentos

**Comment by Leinad4Mind** [comment]
Ah é verdade existe alguns poucos servidores gratuitos que daria para ter as imagens. Como o próprio GitHub.

Se precisar de exemplos reais diga-me.

**Comment by JesusTiag0** [comment]
Boa noite, 

Já testei e esta óptimo, mas diga-me uma coisa, a fotografia que alojamos dentro da pasta tem mesmo que ser referente ao filme ? Desculpe a minha ignorância, mas eu vou tentar explicar o porque de estar a fazer esta pergunta, eu na minhateca tenho os ficheiros todos dentro de pastas, ou seja, quando abro a minhateca tenho uma pasta que diz "filmes HD" outra que diz "Filmes de animação" outra que diz "Filmes 3D" e por ai fora, depois quando abro essas pastas não tenho logo os filmes dentro dela, ainda tenho subpastas cada uma delas com o nome do filme, e para ver as capas tenho que abrir a pasta e só quando vejo o ficheiro é que me aparece a capa, que realmente foi o que eu perguntei se era possível, mas pensava que dava para ficar logo a capa antes de abrir a subpasta, não sei se me estou a fazer entender...!!

Vou meter umas imagens para ver se me consigo explicar melhor, quando abro o kodi na minhateca é isto que me aparece http://i.imgur.com/zEcjTw2.jpg quando abro por exemplo a pasta "filmes hd" é isto que aparece http://i.imgur.com/z3RZJqb.jpg e só depois quando abro uma pasta de um filme realmente me aparece a capa como pode ver http://i.imgur.com/Tipw9mm.jpg a minha duvida é a seguinte, não há a hipótese de se eu meter a imagem com o nome da pasta onde se encontra o filme, e não o nome do filme ? Se não for possível tenho que meter os filmes todos ao molho dentro da pasta, para poder usufruir das capas, mas não era bem essa a minha ideia, não sei se é possível, peço desde já desculpa por estar a ser chato, mas era ouro sobre azul. Outra coisa que também lhe queria perguntar, quando tenho a minhabox ligada não consigo ver nenhum filme da minha conta, é normal ?

Obrigado e mais uma vez peço desculpa.

**Comment by Leinad4Mind** [comment]
Mas qual o problema de ter os filmes ao molhe? Não vai dar ao mesmo que ter pastas ao molhe?
Pessoalmente não vejo nenhuma vantagem.
E mesmo que eu consiga meter a imagem da capa a aparecer na pasta, teria na mesma de entrar na pasta e depois clicar no filme para fazer o play. Ou deseja clicar na pasta e fazer com que isso faça o play automaticamente? 
É que não vejo nenhuma vantagem em ter em pastas... E além disso, ja é possível ocultar as legendas e as imagens. Ou seja ao colocar legenda + vídeo + imagem caso queira... Irá poder ocultar a imagem e a legenda. E dessa forma só irá ver a listagem dos filmes. Tal como se fosse pastas. Talvez a vantagem esteja no facto de não querer mudar os nomes dos ficheiros de vídeo mas querer ter o título do filme no nome da pasta?
Seja como for fazer isso já iria modificar imenso o addon. E já seria outro addon, e seria já algo específico para si.

**Comment by JesusTiag0** [comment]
Boa noite, sim tem toda a razão, cheguei a essa conclusão e já estou a meter mãos a obra, mas agora deparei-me com um pequeno problema! No kodi não aparece a pagina 3 e por ai adiante, passa apenas da 1 para a 2 e é como se não houvesse mais mas eu já tenho 4 paginas e vou ter bastantes mais!!

Obrigado pela atenção

**Comment by Leinad4Mind** [comment]
Ok vou fazer uns testes e averiguar a situação

**Comment by JesusTiag0** [comment]
Boa noite, peço desculpa estar a incomodar mas quando falámos das capas dos filmes por servidor, disse-me que era possível usar o GitHub como servidor de imagens, já dei mil e uma voltas e  não consigo meter as capas, já tentei outros servidores mas também sem êxito, seria possível me explicar como fazer ?

Obrigado desde já pela atenção e paciência.  :)

**Comment by Leinad4Mind** [comment]
Eu averiguei a sua conta e vi que tem tudo bem criado.
Lembre-se que o nome da imagem terá de ser igual a do filme.
E coloque isto como servidor: "raw.githubusercontent.com/JesusTiag0/Capas/master/"

**Comment by JesusTiag0** [comment]
Boa noite, o nome das imagens estão iguais aos dos filmes, mas continua sem aparecer as capas, apenas consigo com a pasta local.
Quando meto para o servidor ele detecta que existe uma imagem para aquele filme,  como pode ver na imagem seguinte http://imgur.com/zuguccI , mas em vez de aparecer a imagem do filme, aparece tudo preto com um símbolo no meio.

Será algum erro meu ou será mesmo mais um erro do add on?

Obrigado

**Comment by Leinad4Mind** [comment]
Tire print à sua configuração.

**Comment by JesusTiag0** [comment]
Bom dia,

A minha configuração esta assim... http://imgur.com/H4V5Nu2

**Comment by Leinad4Mind** [comment]
Com esse tema nem sequer sabes se ficou maiuscula ou minuscula. 
Seja como for se escreveu correctamente o endereço, verifique se o nome dos ficheiros estão iguais. Pois não me parece que estejam.
Na sua imagem vejo: 007 - Spectre ----- [ 2015 ].mkv
E na sua conta github vejo 007 - Spectre ===== [ 2015 ].png
Não é igual... Caso meta igual e não dê, veja se a culpa vem dos [ ] ou dos espaços.
Cumps
