### ISSUE TITLE
Aparece ficheiros .SRT

### ISSUE THREAD

**Issue by JesusTiag0** [Leinad4Mind/leinad4mind-addons#6]
Boa tarde,

Com a nova actualização esta tudo impecavél, menos um pequeno BUG nos ficheiros .SRT, mesmo estando ligada a opção de esconder os ficheiros .SRT e de Imagem, eles continuam a aparecer, e aparece-me também um ficheiro na pasta principal que não existe lá, mas sim dentro de uma Subpasta.

**Comment by Leinad4Mind** [comment]
Irei averiguar esta semana. Isso é algo fácil de se corrigir. Quanto ao tal ficheiro que aparece na pasta principal isso só acontece se tiver ficheiros públicos. Deve ter tudo na pasta privada para não ter esse bug, que não tenho vontade de resolver visto que o propósito é ter tudo na privada.

**Comment by JesusTiag0** [comment]
Boa tarde,

Como assim ter na privada, peço desculpa mas nao entendi, o ficheiro que me aparece na pasta raiz, encontra-se dentro da pasta classicos Disney, e aparece-me como se tivesse entre as pastas e com um tamanho de ( 0 ).
É assim que tenho no site minhateca http://imgur.com/kLLlCjY e assim aparece-me no KODI http://imgur.com/Gyp75Q9

**Comment by JesusTiag0** [comment]
Já entendi, acabei de introduzir uma password na pasta onde tinha o filme, e deixou de aparecer, assim sendo é mesmo apenas os ficheiros .SRT.

Obrigado pela resposta tão rapida, apenas tenho mais uma pergunta, peço desculpa de ser tão chato.
Não existe a hipotesse de meter penso que se chama fanart, por tras das capas quando escolhermos o filme ? Nem que seja apenas para todas as pastas, para não ficar com o fundo preto ?

Obrigado

**Comment by Leinad4Mind** [comment]
Para meter atrás de cada filme só se fosse .PNG para capas e .Jpg para fundos. Teriam de ter extensões diferentes e dessa forma já facilmente adicionaria esse extra.

**Comment by JesusTiag0** [comment]
Obrigado na mesma. 

Diga-me apenas mais uma coisa, peço desculpa tanta pergunta, imagine que eu gostaria de criar um add-on ou melhor um add-on já criado, existe algum programa para o fazer ou é apenas por programação ? É que de programação nao entendo muito, e apenas lhe meto problemas, e gostava de puder ajudar em vez de apenas complicar.

Obrigado

**Comment by Leinad4Mind** [comment]
Mesmo que use um IDE precisaria de programar na mesma. Eu nem me dou ao
trabalho de instalar o IDE faço no notepad++ que chega e sobra para este
efeito.

Em 23/01/2017 16:45, "JesusTiag0" <notifications@github.com> escreveu:
