### ISSUE TITLE
addons copiadb error  kbagi.com

### ISSUE THREAD

**Issue by xiquillo** [Leinad4Mind/leinad4mind-addons#9]
hi, the addons copiadb the option kbagi to stop working, before I put the user and password and worked since yesterday to stop working when I enter my files nothing comes out this empty. I hope that in a new update you correct it. thanks for this addons so good for those who usamoa kbagi.com. thank you

**Comment by Leinad4Mind** [comment]
The problem was solved today. I'll submit a new release very soon
